apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bleachdle.fullname" . }}-configmap
data:
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
  API_URL: {{ .Values.config.API_URL | quote }}
