apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bleachdle.fullname" . }}-secrets
type: Opaque
data:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
