{{- /*
     ServiceMonitor picked up by kube‑prometheus‑stack.
*/ -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bleachdle.fullname" . }}-sm
  labels:
    release: prom-stack            # must match .Release.Name of the Prom stack
spec:
  selector:
    matchLabels:
      app: {{ include "bleachdle.name" . }}
  namespaceSelector:
    matchNames: 
      - {{ .Release.Namespace }}
  endpoints:
    - port: http                   # maps to servicePort name below
      path: /metrics
      interval: 15s
