apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bleachdle.fullname" . }}-sm
  
  labels:
    app.kubernetes.io/component: bleachdle
  
spec:
  selector:
    matchLabels:
      app: {{ include "bleachdle.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
