apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bleachdle
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ILAN-GiM3L/BleachdleWeb.git"
    targetRevision: "main"
    path: "helm/bleachdle"
    helm:
      releaseName: bleachdle
  destination:
    name: bleachdle-ephemeral  # destination cluster name from Terraform
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
