apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: "70.5.0"
    helm:
      values: |
        grafana:
          enabled: false
        alertmanager:
          enabled: true
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
          tls:
            enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
          service:
            type: LoadBalancer
            port: 9090
            targetPort: 9090
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
