apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    # 70.5.0 = latest (15 Apr 2025) :contentReference[oaicite:0]{index=0}
    targetRevision: "70.5.0"
    helm:
      # Disable components you already have
      values: |
        grafana:
          enabled: false        # we run Grafana separately
        alertmanager:
          enabled: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
          service:
            type: LoadBalancer     # exposes :9090 externally
            port: 9090
            targetPort: 9090

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
