# argocd-apps/child-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: "vault"
    targetRevision: "0.24.0"  # We keep 0.24.0 as you originally had
    helm:
      releaseName: "vault"
      values: |-
        injector:
          enabled: true

        server:
          # Force HA off (single Vault instance, though it uses a StatefulSet)
          ha:
            enabled: false

          # Security context that lets non-root user (UID 100) read secrets
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 100
            fsGroup: 100

          # Provide the GCP KMS seal config here
          config: |
            ui = true
            listener "tcp" {
              address     = "0.0.0.0:8200"
              tls_disable = true
            }
            storage "file" {
              path = "/vault/data"
            }
            seal "gcpckms" {
              project     = "bleachdle-web"
              region      = "us-central1"
              key_ring    = "vault-key-ring"
              crypto_key  = "vault-key"
              credentials = "/vault/config/gcp-creds.json"
            }

          # Environment vars to reference the credentials path
          extraEnvironmentVars:
            GCP_PROJECT: "bleachdle-web"
            GCP_REGION: "us-central1"
            GOOGLE_APPLICATION_CREDENTIALS: "/vault/config/gcp-creds.json"

          # Mount the GCP creds secret as a single file
          extraVolumes:
            - name: vault-gcp-creds
              secret:
                secretName: vault-gcp-creds

          extraVolumeMounts:
            - name: vault-gcp-creds
              mountPath: /vault/config/gcp-creds.json
              subPath: gcp-creds.json
              readOnly: true

  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
