# argocd-apps/child-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/hashicorp/vault-helm.git"
    targetRevision: "v0.23.0"   # Adjust if desired
    path: "."
    helm:
      releaseName: vault
      values: |
        server:
          # Disable dev mode, enable single-instance (standalone) mode
          dev:
            enabled: false
          standalone:
            enabled: true
            # This inline config block is the recommended way to set up auto-unseal
            config: |
              ui = true

              listener "tcp" {
                address     = "[::]:8200"
                tls_disable = 1
              }

              # GCP KMS seal stanza
              seal "gcpckms" {
                project     = "bleachdle-web"
                region      = "us-central1"
                key_ring    = "vault-key-ring"
                crypto_key  = "vault-key"
              }

              # Store data on the local filesystem (within this pod's PV)
              storage "file" {
                path = "/vault/data"
              }

            # Provision a small PersistentVolumeClaim for Vault data
            dataStorage:
              enabled: true
              size: 1Gi

            # Mount the GCP service account file from our Secret
            extraEnvironmentVars:
              GOOGLE_APPLICATION_CREDENTIALS: "/etc/vault/gcp/gcp-creds.json"

            extraVolumes:
              - name: gcp-creds
                secret:
                  secretName: vault-gcp-creds

            extraVolumeMounts:
              - name: gcp-creds
                mountPath: /etc/vault/gcp
                readOnly: true

        # Disable the Vault Agent Injector if you're using a sidecar approach
        injector:
          enabled: false

  # Deploys Vault to the ephemeral cluster named "bleachdle-ephemeral"
  destination:
    name: bleachdle-ephemeral
    namespace: vault

  # Auto-sync & self-heal keeps Vault in sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
