apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secret-role-binding
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ILAN-GiM3L/BleachdleWeb.git"
    targetRevision: "main"
    path: "argocd-apps/child-apps"
    # This should point to where the RBAC YAML is stored
    directory:
      recurse: true
  destination:
    name: bleachdle-ephemeral  # Ensure this matches your GKE cluster name
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vault
  name: vault-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]  # ConfigMaps are included for completeness
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secret-access
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: bleachdle-sa
    namespace: default  # Make sure 'default' is the correct namespace for bleachdle-sa
roleRef:
  kind: Role
  name: vault-secret-reader
  apiGroup: rbac.authorization.k8s.io
