apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    # Use the official HashiCorp Vault Helm chart repository. 
    # You can pin a specific version or branch if you prefer.
    repoURL: "https://github.com/hashicorp/vault-helm.git"
    targetRevision: "v0.23.0" 
    path: "."             # The root folder of the vault-helm repo
    helm:
      releaseName: "vault"
      values: |
        global:
          # Enables common labeling
          enabled: true

        # ----------------------------------------------------------------------
        # Vault Server configuration
        # ----------------------------------------------------------------------
        server:
          # Run a "real" Vault server, not dev mode
          dev:
            enabled: false

          # We won't enable HA or external data storage
          ha:
            enabled: false
          dataStorage:
            enabled: false

          # Mount the GCP credentials secret for auto-unseal
          extraVolumes:
            - name: vault-gcp-creds
              secret:
                secretName: vault-gcp-creds
                optional: false
          extraVolumeMounts:
            - name: vault-gcp-creds
              mountPath: /vault/config
              readOnly: true

          # This is the Vault server configuration (vault.hcl).
          # It enables UI, sets up the listener, and configures GCP KMS for auto-unseal.
          config: |
            ui = true

            listener "tcp" {
              address     = "0.0.0.0:8200"
              tls_disable = 1
            }

            # GCP KMS auto-unseal block:
            seal "gcpckms" {
              project     = "bleachdle-web"
              region      = "us-central1"
              key_ring    = "vault-key-ring"
              crypto_key  = "vault-key"
              # Matches the Jenkins pipeline's secretMount path
              credentials = "/vault/config/gcp-creds.json"
            }

            # Adjust the addresses to match your environment
            api_addr     = "http://vault.vault.svc:8200"
            cluster_addr = "https://vault.vault.svc:8201"

  # --------------------------------------------------------------------------
  # Destination: ephemeral cluster, in the "vault" namespace
  # (Your Jenkins pipeline has code that registers the ephemeral cluster
  #  under the name "bleachdle-ephemeral".)
  # --------------------------------------------------------------------------
  destination:
    name: "bleachdle-ephemeral"
    namespace: "vault"

  # --------------------------------------------------------------------------
  # Sync automatically: if anything changes, Argo CD prunes old resources
  # and self-heals if resources drift.
  # --------------------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
