# argocd-apps/child-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: "vault"
    targetRevision: "0.24.0"
    helm:
      releaseName: "vault"
      values: |-
        # Enable the Vault injector (sidecar)
        injector:
          enabled: true

        # Main Vault server settings:
        server:
          # We want a single-node "standalone" setup, so disable HA:
          ha:
            enabled: false

          # Enable the standalone approach with a single replica
          standalone:
            enabled: true
            replicas: 1

            # This is your Vault configuration, merged into the final ConfigMap
            config: |
              ui = true
              listener "tcp" {
                address     = "0.0.0.0:8200"
                tls_disable = true
              }
              storage "file" {
                path = "/vault/data"
              }
              seal "gcpckms" {
                project     = "bleachdle-web"
                region      = "us-central1"
                key_ring    = "vault-key-ring"
                crypto_key  = "vault-key"
                credentials = "/vault/gcp-creds/gcp-creds.json"
              }

          # =====  Everything below goes at the *server* level =====
          # Extra environment variables for the main Vault container
          extraEnv:
            - name: GCP_PROJECT
              value: "bleachdle-web"
            - name: GCP_REGION
              value: "us-central1"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/vault/gcp-creds/gcp-creds.json"

          # An init container that writes your GCP creds into an emptyDir volume
          extraInitContainers:
            - name: write-gcp-creds
              image: busybox
              command:
                - sh
                - -c
                - 'echo "$GCP_CREDS" > /vault/gcp-creds/gcp-creds.json'
              env:
                - name: GCP_CREDS
                  valueFrom:
                    secretKeyRef:
                      name: vault-gcp-creds    # Must match the Secret you created
                      key: gcp-creds.json
              volumeMounts:
                - name: creds-volume
                  mountPath: /vault/gcp-creds

          # An emptyDir volume to hold that credentials file
          extraVolumes:
            - name: creds-volume
              emptyDir: {}

          # Mount that volume inside the primary Vault container
          extraVolumeMounts:
            - name: creds-volume
              mountPath: /vault/gcp-creds

  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
