# argocd-apps/child-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: "vault"
    targetRevision: "0.24.0"
    helm:
      releaseName: "vault"
      values: |-
        injector:
          enabled: true

        server:
          # Force HA off so we only deploy a Deployment (not a StatefulSet)
          ha:
            enabled: false

          standalone:
            enabled: true
            replicas: 1

            # Add a securityContext so the Vault process (UID 100) can read mounted secrets
            securityContext:
              runAsNonRoot: true
              runAsUser: 100
              runAsGroup: 100
              fsGroup: 100

            config: |
              ui = true
              listener "tcp" {
                address     = "0.0.0.0:8200"
                tls_disable = true
              }
              storage "file" {
                path = "/vault/data"
              }
              seal "gcpckms" {
                project     = "bleachdle-web"
                region      = "us-central1"
                key_ring    = "vault-key-ring"
                crypto_key  = "vault-key"
                credentials = "/vault/config/gcp-creds.json"
              }

            extraEnvironmentVars:
              GCP_PROJECT: "bleachdle-web"
              GCP_REGION: "us-central1"
              GOOGLE_APPLICATION_CREDENTIALS: "/vault/config/gcp-creds.json"

            extraVolumes:
              - name: vault-gcp-creds
                secret:
                  secretName: vault-gcp-creds

            extraVolumeMounts:
              - name: vault-gcp-creds
                # Instead of mounting the entire /vault/config directory,
                # mount only one file as /vault/config/gcp-creds.json
                mountPath: /vault/config/gcp-creds.json
                subPath: gcp-creds.json
                readOnly: true

  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
