apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/hashicorp/vault-helm.git"
    targetRevision: "v0.23.0"
    path: "."
    helm:
      releaseName: vault
      values: |   # <-- Start an inline YAML block for our overrides
        server:
          dev:
            enabled: false

          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                address     = "[::]:8200"
                tls_disable = 1
              }
              seal "gcpckms" {
                project    = "bleachdle-web"
                region     = "us-central1"
                key_ring   = "vault-key-ring"
                crypto_key = "vault-key"
              }
              storage "file" {
                path = "/vault/data"
              }
            dataStorage:
              enabled: true
              size: 10Gi

          extraEnvironmentVars:
            GOOGLE_APPLICATION_CREDENTIALS: "/etc/vault/gcp/gcp-creds.json"

          extraVolumes:
            - name: gcp-creds
              secret:
                secretName: vault-gcp-creds

          extraVolumeMounts:
            - name: gcp-creds
              mountPath: /etc/vault/gcp
              readOnly: true

        injector:
          enabled: false

  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
