# argocd-apps/child-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    # Points to the official HashiCorp Vault Helm chart (adjust version as needed).
    repoURL: "https://github.com/hashicorp/vault-helm.git"
    targetRevision: "v0.23.0"
    path: "."
    helm:
      releaseName: vault
      values: |
        injector:
          enabled: false

        server:
          ha:
            enabled: false

          # Create a small PersistentVolume for Vault data
          dataStorage:
            enabled: true
            size: 1Gi

          # Set env var for GCP credentials
          extraEnvironmentVars:
            GOOGLE_APPLICATION_CREDENTIALS: "/etc/vault/gcp/gcp-creds.json"

          # Mount the secret containing the GCP service account JSON
          extraVolumes:
            - name: gcp-creds
              secret:
                secretName: vault-gcp-creds
          extraVolumeMounts:
            - name: gcp-creds
              mountPath: /etc/vault/gcp
              readOnly: true

          # IMPORTANT: Combine auto-unseal arguments into a single string
          extraArgs: "-config=/vault/config/config.json -seal=gcpckms -seal-gcpckms-project=bleachdle-web -seal-gcpckms-region=us-central1 -seal-gcpckms-key-ring=vault-key-ring -seal-gcpckms-crypto-key=vault-key"

  # Deploy onto the ephemeral cluster named "bleachdle-ephemeral"
  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
