# argocd-apps/child-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: "vault"
    targetRevision: "0.24.0"
    helm:
      releaseName: "vault"
      values: |-
        injector:
          enabled: true

        server:
          ha:
            enabled: false

          standalone:
            enabled: true
            replicas: 1
            securityContext:
              runAsNonRoot: true
              runAsUser: 100
              runAsGroup: 100
              fsGroup: 100
            config: |
              ui = true
              listener "tcp" {
                address     = "0.0.0.0:8200"
                tls_disable = true
              }
              storage "file" {
                path = "/vault/data"
              }
              seal "gcpckms" {
                project     = "bleachdle-web"
                region      = "us-central1"
                key_ring    = "vault-key-ring"
                crypto_key  = "vault-key"
                credentials = "/vault/gcp-creds/gcp-creds.json"
              }
          extraEnvironmentVars:
            GCP_PROJECT: "bleachdle-web"
            GCP_REGION: "us-central1"
            GOOGLE_APPLICATION_CREDENTIALS: "/vault/gcp-creds/gcp-creds.json"
          extraVolumes:
            - name: creds-volume
              emptyDir: {}
          initContainers:
            - name: write-gcp-creds
              image: busybox
              command: ["sh", "-c", "echo \"$GCP_CREDS\" > /vault/gcp-creds/gcp-creds.json"]
              env:
                - name: GCP_CREDS
                  valueFrom:
                    secretKeyRef:
                      name: vault-gcp-creds
                      key: gcp-creds.json
              volumeMounts:
                - name: creds-volume
                  mountPath: /vault/gcp-creds
          extraVolumeMounts:
            - name: creds-volume
              mountPath: /vault/gcp-creds

  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
