apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bleachdle.fullname" . }}
  labels:
    {{- include "bleachdle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bleachdle.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bleachdle.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-inject-secret-app: "{{ .Values.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-app: |
          {{`{{- with secret "bleach/data/app" -}}`}}
          export DB_HOST={{`{{ .Data.data.db_host }}`}}
          export DB_USER={{`{{ .Data.data.db_user }}`}}
          export DB_PASSWORD={{`{{ .Data.data.db_password }}`}}
          export DB_NAME={{`{{ .Data.data.db_name }}`}}
          export API_URL={{`{{ .Data.data.api_url }}`}}
          {{`{{- end }}`}}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: vault-sidecar  
          image: "hashicorp/vault:1.13.1"
          command: ["/bin/sh"]
          args:
            - "-ec"
            - |
              apk add --no-cache curl
              while ! wget -q --spider http://vault.vault.svc:8200/v1/sys/health; do
                echo "Waiting for Vault..."
                sleep 5
              done
              echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json

        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - ". /vault/secrets/app && exec python app.py"
