apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "bleachdle.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: terraform-admin@bleachdle-web.iam.gserviceaccount.com
