apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: default
  labels:
    {{- include "bleachdle.labels" . | nindent 4 }}
automountServiceAccountToken: true
