# argocd-apps/bleachdle-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bleachdle
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://github.com/ILAN-GiM3L/BleachdleWeb.git"
    targetRevision: "main"
    path: "helm"          # path to your Chart.yaml
    helm:
      releaseName: bleachdle
      values: |
        replicaCount: 1
        image:
          repository: ilangimel/bleachdle-web-app
          tag: latest
        service:
          type: LoadBalancer
          port: 5000
          targetPort: 5000
          nodePort: 32000
        vault:
          role: "bleachdle-role"
          secretPath: "bleach/data/app"
          skipVerify: true
        serviceAccount:
          create: false
          name: "bleachdle-sa"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
