# argocd-apps/vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd   # Must exist in the same cluster & namespace as Argo CD
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: "0.24.0"
    chart: "vault"
    helm:
      releaseName: vault
      values: |-
        injector:
          enabled: true
        server:
          # High-availability, root token, auto-unseal w/ GCP
          ha:
            enabled: true
            replicas: 1
            initialRootToken: "root"
          extraEnvironmentVars:
            GCP_PROJECT: "bleachdle-web"
            GCP_REGION: "us-central1"
            GOOGLE_APPLICATION_CREDENTIALS: "/vault/config/gcp-creds.json"
          config: |
            ui = true
            listener "tcp" {
              address = "0.0.0.0:8200"
              tls_disable = true
            }
            storage "file" {
              path = "/vault/data"
            }
            seal "gcpckms" {
              project     = "bleachdle-web"
              region      = "us-central1"
              key_ring    = "vault-key-ring"
              crypto_key  = "vault-key"
              credentials = "/vault/config/gcp-creds.json"
            }
          extraVolumes:
            - name: vault-gcp-creds
              secret:
                secretName: vault-gcp-creds
          extraVolumeMounts:
            - name: vault-gcp-creds
              mountPath: /vault/config
              readOnly: true
  destination:
    name: bleachdle-ephemeral  # reference ephemeral cluster by name
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
