# vault-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    # "Helm" type with 'chart' & 'repoURL', not a Git repo
    chart: vault
    repoURL: "https://helm.releases.hashicorp.com"
    targetRevision: "0.23.0"   # or "latest"
    helm:
      releaseName: vault
      valueFiles:
        - vault-values.yaml

  destination:
    name: bleachdle-ephemeral
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
