# vault-values.yaml
server:
  dev:
    enabled: false

  # Single-instance "standalone" mode
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address     = "[::]:8200"
        tls_disable = 1
      }

      # GCP KMS Seal Stanza
      seal "gcpckms" {
        project    = "bleachdle-web"
        region     = "us-central1"
        key_ring   = "vault-key-ring"
        crypto_key = "vault-key"
      }

      # File-based storage
      storage "file" {
        path = "/vault/data"
      }

    # Create a small PersistentVolume for the data
    dataStorage:
      enabled: true
      size: 1Gi

  # MOUNT THE GCP CREDS
  extraEnvironmentVars:
    GOOGLE_APPLICATION_CREDENTIALS: "/etc/vault/gcp/gcp-creds.json"

  extraVolumes:
    - name: gcp-creds
      secret:
        secretName: vault-gcp-creds

  extraVolumeMounts:
    - name: gcp-creds
      mountPath: /etc/vault/gcp
      readOnly: true

injector:
  enabled: false
