replicaCount: 1

image:
  repository: ilangimel/bleachdle-web-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000
  nodePort: 32000

vault:
  role: "bleachdle-role"
  # IMPORTANT: Use the same path that Terraform configures (i.e., "bleach/data/app")
  secretPath: "bleach/data/app"

serviceAccount:
  create: true
  name: "bleachdle-sa"
